version: '3.8'

services:
    db:
        image: mysql:latest
        container_name: delivery-db
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: delivery
        ports:
            - "3306:3306"
        volumes:
            - ./storage/logs/mysql:/var/log/mysql
            - ./mysql-data:/var/lib/mysql
        networks:
            - delivery
    php:
        build:
            context: docker/php
        container_name: delivery-php
        volumes:
            - .:/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
        networks:
            - delivery
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: delivery-nginx
        working_dir: /www
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - .:/www
            - ./docker/nginx:/etc/nginx/conf.d
            - ./storage/logs/nginx:/var/log/nginx
        networks:
            - delivery
        depends_on:
            - php

networks:
    delivery:
        driver: bridge
